kind: pipeline
name: default
steps:
- name: docker
  image: plugins/docker
  settings:
      username:
        from_secret: docker-user
      password:
        from_secret: docker-password
      custom_dns: [ 192.168.1.1 ]
      repo: registry.m17project.org/m17/m17-spec
      registry: registry.m17project.org
      tags: latest
